project:
  type: website

website:
  title: ""
  navbar:
    logo: assets/biomes.png # Path to your logo image
    left:
      #- href: index.qmd
       # text: Home
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
      - href: partners_and_collaborators.qmd
        text: Partners

format:
  html:
    theme: flatly
    css: 
      - styles.css
      - custom.css
    toc: true
    toc-depth: 3
    toc-title: Contents
    number-sections: true
    highlight-style: github
    code-fold: true
    code-tools: false
    mainfont: Helvetica

editor: visual

