project:
  type: website
website:
  title: ""
  navbar:
    logo: assets/biomes.png
    left:
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
      - href: partners_and_collaborators.qmd
        text: Partners
  page-footer: 
    center: 
      - text: "The content on this website is for informational purposes only. © BIOMES - All rights reserved."
    background: white
format:
  html:
    theme: flatly
    css: 
      - styles.css
      - custom.css
    toc: true
    toc-depth: 3
    toc-title: " "
    number-sections: false
    highlight-style: github
    code-fold: true
    code-tools: false
    mainfont: Helvetica
editor: visual